server:
  port: 9001

spring:
  application:
    name: USER-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true


management:
  endpoints:
    web:
      exposure:
        include: health,bean,info,